package com.digisailor.order_server.service;

import com.digisailor.grpc.CreateOrderRequest;
import com.digisailor.grpc.OrderResponse;
import com.digisailor.grpc.OrderServiceGrpc;
import com.digisailor.grpc.OrderStatus;
import com.digisailor.order_server.entity.Order;
import com.digisailor.order_server.repository.OrderRepository;
import io.grpc.stub.StreamObserver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class OrderServiceImpl extends OrderServiceGrpc.OrderServiceImplBase {

    private final OrderRepository orderRepository;

    @Autowired
    public OrderServiceImpl(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }

    @Override
    public void createOrder(CreateOrderRequest request, StreamObserver<OrderResponse> responseObserver) {
        // Create and save the new order
        Order order = new Order();
        order.setStatus(OrderStatus.PLACED); // Set initial status

        // Save order to the database
        order = orderRepository.save(order);

        // Build the response
        OrderResponse response = OrderResponse.newBuilder()
                .setOrderId(order.getId()) // Use the ID generated by the database
                .setStatus(OrderStatus.valueOf(order.getStatus().name())) // Map entity OrderStatus to gRPC OrderStatus
                .build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}